export const apiUrl = "https://geoone.viansoftware.com.br";
export const mapsKey = "AIzaSyDsv3y2gYgSoEusZRMv-wLNPjp-F6xAnF4";
export const methodologies = [
  "VM0001 Metodologia de Projeto de Eficiência de Detecção Automática de Vazamento de Refrigerante por Infravermelho, v1.1",
  "VM0002 Novas instalações de cogeração que fornecem eletricidade com menos carbono à rede e/ou água quente para um ou mais clientes da rede, v1.0",
  "VM0003 Metodologia para Melhor Manejo Florestal por meio da Extensão da Idade de Rotação, v1.2",
  "VM0004 Metodologia para projetos de conservação que evitam a conversão planejada do uso da terra em florestas de turfa",
  "VM0005 Metodologia para Conversão de Floresta de Baixa Produtividade em Floresta de Alta Produtividade, v1.2",
  "VM0006 Metodologia para Contabilidade de Carbono para Projetos de REDD em Mosaico e Escala de Paisagem, v2.2",
  "VM0007 Estrutura Metodológica de REDD+ (REDD-MF), v1.6",
  "VM0008 Climatização de Edifícios Unifamiliares e Multifamiliares, v1.1",
  "VM0009 Metodologia para evitar a conversão do ecossistema, v3.0",
  "VM0010 Metodologia para Melhor Manejo Florestal: Conversão de Floresta Registrada para Floresta Protegida, v1.3",
  "VM0011 Metodologia para calcular os benefícios de GEE da prevenção da degradação planejada, v1.0",
  "VM0012 Manejo florestal aprimorado em florestas temperadas e boreais (LtPF), v1.2",
  "VM0013 Cálculo das reduções de emissões da lavagem de motores a jato, v1.0",
  "VM0014 Intercepção e destruição de metano fugitivo de infiltrações de metano de leito de carvão (CBM), v1.0",
  "VM0015 Metodologia para evitar o desmatamento não planejado, v1.1",
  "VM0016 Recuperação e Destruição de Substâncias Destruidoras de Ozônio (SDO) de Produtos, v1.1",
  "VM0017 Adoção de Gestão Sustentável de Terras Agrícolas, v1.0",
  "VM0018 Eficiência Energética e Atividades de Desvio de Resíduos Sólidos em uma Comunidade Sustentável, v1.0",
  "VM0019 Troca de Combustível de Gasolina para Etanol em Frotas de Veículos Flex-Fuel, v1.0",
  "VM0020 Eficiência energética de transporte de paletes leves, v1.0",
  "VM0021 Metodologia de Quantificação de Carbono no Solo, v1.0",
  "VM0022 Quantificando as Reduções de Emissões de N2O em Culturas Agrícolas por meio da Redução da Taxa de Fertilizantes Nitrogenados, v1.1",
  "VM0023 Redução de Emissões de GEE na Produção de Óxido de Propileno, v1.0",
  "VM0024 Metodologia para Criação de Zona Húmida Costeira, v1.0",
  "VM0025 Campus Energia Limpa e Eficiência Energética",
  "VM0026 Metodologia para Manejo de Campos Sustentáveis ​​(SGM)",
  "VM0027 Metodologia para Reumedecimento de Turfeiras Tropicais Drenadas, v1.0",
  "VM0028 Metodologia para caronas",
  "VM0029 Metodologia para Degradação Florestal Evitada pelo Manejo do Fogo, v1.0",
  "VM0030 Metodologia para Aplicação de Pavimento com Substituto de Enxofre, v1.0",
  "VM0031 Metodologia para Produção de Concreto Pré-moldado com Substituto Enxofre, v1.0",
  "VM0032 Metodologia para Adoção de Campos Sustentáveis ​​por meio da Adequação do Fogo e Pastejo",
  "VM0033 Metodologia para Restauração de Pantanal de Maré e Ervas Marinhas, v1.0",
  "VM0034 Metodologia de Compensação de Carbono Florestal da Colúmbia Britânica, v1.0",
  "VM0035 Metodologia para Melhor Manejo Florestal por Meio da Exploração de Impacto Reduzido v1.0",
  "VM0036 Metodologia para reumedecimento de turfeiras temperadas drenadas, v1.0",
  "VM0037 Metodologia para Implementação de Atividades de REDD+ em Paisagens Afetadas por Desmatamento e Degradação em Mosaico, v1.0",
  "VM0038 Metodologia para Sistemas de Carregamento de Veículos Elétricos, v1.0",
  "VM0039 Metodologia para Uso de Base Estabilizada por Espuma e Misturas de Emulsão Asfáltica em Aplicação de Pavimento, v1.0",
  "VM0041 Metodologia para Redução de Emissões de Metano Entérico de Ruminantes através do Uso de Suplemento Alimentar 100% Natural, v1.0",
  "VM0042 Metodologia para Melhor Gestão de Terras Agrícolas, v1.0",
  "VM0043 Metodologia para Utilização de CO 2  na Produção de Concreto",
  "VM0044 Metodologia para Utilização de Biochar em Aplicações Solo e Não Solo, v1.0",
  "VM0045 Metodologia de Manejo Florestal Aprimorada Usando Linhas de Base Combinadas Dinâmicas de Inventários Florestais Nacionais, V1.0",
  "VMR0001 Revisões para ACM0008 para Incluir a Pré-drenagem de Metano de uma Mina Aberta Ativa como uma Atividade de Redução de Emissão de Metano, v1.0",
  "VMR0002 Revisões para ACM0008 para Incluir Captura e Destruição de Metano de Minas de Carvão Abandonadas, v1.0",
  "VMR0003 Revisões para AMS-III.Y para incluir o uso de material de cama orgânico, v1.0",
  "VMR0004 Revisões para AMS-III.BC para Incluir Máquinas Móveis, v1.0",
  "VMR0005 Metodologia para Instalação de Dispositivos de Baixa Vazão de Água, v1.0",
  "VMR006 Metodologia para Instalação de Fogões a Lenha de Alta Eficiência",
];

export const states = [
  "Acre",
  "Alagoas",
  "Amapá",
  "Amazonas",
  "Bahia",
  "Ceará",
  "Distrito Federal",
  "Espírito Santo",
  "Goiás",
  "Maranhão",
  "Mato Grosso",
  "Mato Grosso do Sul",
  "Minas Gerais",
  "Pará",
  "Paraíba",
  "Paraná",
  "Pernambuco",
  "Piauí",
  "Rio de Janeiro",
  "Rio Grande do Norte",
  "Rio Grande do Sul",
  "Rondônia",
  "Roraima",
  "Santa Catarina",
  "São Paulo",
  "Sergipe",
  "Tocantins",
];

export const projectType = [
  "Agricultura Silvicultura e Outros Usos da Terra",
  "Indústria química",
  "Construção",
  "Demanda energética",
  "distribuição de energia",
  "Indústrias de energia (fontes renováveis/não renováveis)",
  "Emissões fugitivas de combustíveis (sólidos, petróleo e gás)",
  "Emissões fugitivas da produção e consumo de halocarbonos e hexafluoreto de enxofre",
  "Pecuária, fermentação entérica e manejo de esterco",
  "Indústrias manufatureiras",
  "Produção de metais",
  "Mineração/produção mineral",
  "Transporte",
  "Manuseio e descarte de resíduos",
];

 export const projectStatus = [
   "Renovação do Período de Crédito e Aprovação de Verificação Solicitada",
   "Solicitação de Renovação do Período de Crédito",
   "Inativo",
   "Em espera",
   "Registrado",
   "Aprovação de registro e verificação solicitada",
   "Registro solicitado",
   "Rejeitado pelo administrador",
   "Em desenvolvimento",
   "Em validação",
   "Unidades Transferidas do Programa de GEE Aprovado",
   "Retirado",
 ];
